apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: elasticsearch
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AdamMilen/elasticsearch-assignment.git
    targetRevision: dev
    path: argocd/user-apps/elasticsearch
  destination: 
    server: https://kubernetes.default.svc
    namespace: elastic-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true