podAnnotations:
  linkerd.io/inject: enabled
service:
  labels: 
    operated-prometheus: "true"
es:
  uri: http://elastic:adminadmin@elastic-linkerd-es-http.elastic-system.svc.cluster.local:9200
  sslSkipVerify: true