# basic elasticsearch alert
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus-operator
  name: elasticsearch-rule
  namespace: monitoring
spec:
  groups:
  - name: Elasticsearch
    rules:

      # elasticsearch cluster can still function because node 2 has the replicated data of node 3
      - alert: ElasticsearchTooFewNodesRunning
        expr: elasticsearch_cluster_health_number_of_nodes < 3
        for: 5m
        labels:
          severity: warning
          app: elasticsearch
        annotations:
          summary: "Elasticsearch running on less than 3 nodes"
          description: "There are only {{$value}} < 3 Elasticsearch nodes running."
      
      # elasticsearch cluster lose data beacause node 1 cannot hold the replciated data of node 2 and 3
      - alert: ElasticsearchTooFewNodesRunning
        expr: elasticsearch_cluster_health_number_of_nodes < 2
        for: 5m
        labels:
          severity: critical
          app: elasticsearch
        annotations:
          summary: "Elasticsearch running on less than 2 nodes"
          description: "There are only {{$value}} < 2 Elasticsearch nodes running."
      
      - alert: ElasticsearchTooManyOpenFiles
        expr: elasticsearch_process_open_files_count > 60000
        for: 5m
        labels:
          severity: critical
          app: elasticsearch
        annotations:
          summary: "Elasticsearch has too many open files"
          description: "The number of open file descriptors is above 60,000, which may cause failures"

      - alert: ElasticsearchHighDiskUsage
        expr: (elasticsearch_filesystem_data_available_bytes / elasticsearch_filesystem_data_size_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
          app: elasticsearch
        annotations:
          summary: "Elasticsearch high disk usage"
          description: "An elasticsearch node has less than 20% free disk space."

      - alert: ElasticsearchHeapUsageTooHigh
        expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 0.9
        for: 15m
        labels:
          severity: critical
          app: elasticsearch
        annotations:
          summary: "Elasticsearch node {{$labels.node}} heap usage is high"
          description: "The heap usage is over 90% for 15m"